# Created with YamlCreate.ps1 v2.1.2 $debug=AUSU.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Novicon.Munixo.Client
PackageVersion: 5.0.65.14161
PackageLocale: en-US
Publisher: Novicon GmbH
PublisherUrl: http://www.novicon.net/
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: munixo Client
PackageUrl: https://www.munixo.com/
License: Proprietary
# LicenseUrl: 
Copyright: Copyright (C) 2022 Novicon GmbH
# CopyrightUrl: 
ShortDescription: GUI client for managing Munixo ERP Systems
Description: >
  Munixo is the lean and intuitive ERP software especially for medium-sized companies in the retail, service, food and pharmaceutical industries.
  Processes and data can be checked, controlled and optimized centrally at any time and from anywhere. Thanks to Munixo, all relevant company key
  figures are always live and always in focus. Customer-specific adjustments and developments enable the optimal solution for your company.
# Moniker: 
Tags: 
- erp
- enterprise_resource_planning
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
